require 'rubygems'
gem 'mime-types', version: '=1.16'
require 'rest_connection'
require 'time'
require 'mail'
require 'resolv'
require 'logger'
require 'json'
require 'yaml'
require 'highline/import'
