---
:server_hours: 24
:volume_hours: 168
:snapshot_hours: 672
:safe_words: 
  - save
:user_email: true
:admin_email: ryan@rightscale.com
:disable_email: false
:tag: terminator
:terminator_login: terminator@cloudie.us
:terminator_password: R!ght5cale
:account_ids:
  - 7954
